/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLHome`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLMovilidad`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLReportProblem`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLRoomS`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLServices`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextHome`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextMovilidad`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextReportProblem`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextRoomS`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextServices`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/ASL/ASLHome`; params?: Router.UnknownOutputParams; } | { pathname: `/ASL/ASLMovilidad`; params?: Router.UnknownOutputParams; } | { pathname: `/ASL/ASLReportProblem`; params?: Router.UnknownOutputParams; } | { pathname: `/ASL/ASLRoomS`; params?: Router.UnknownOutputParams; } | { pathname: `/ASL/ASLServices`; params?: Router.UnknownOutputParams; } | { pathname: `/Text/TextHome`; params?: Router.UnknownOutputParams; } | { pathname: `/Text/TextMovilidad`; params?: Router.UnknownOutputParams; } | { pathname: `/Text/TextReportProblem`; params?: Router.UnknownOutputParams; } | { pathname: `/Text/TextRoomS`; params?: Router.UnknownOutputParams; } | { pathname: `/Text/TextServices`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/ASL/ASLHome${`?${string}` | `#${string}` | ''}` | `/ASL/ASLMovilidad${`?${string}` | `#${string}` | ''}` | `/ASL/ASLReportProblem${`?${string}` | `#${string}` | ''}` | `/ASL/ASLRoomS${`?${string}` | `#${string}` | ''}` | `/ASL/ASLServices${`?${string}` | `#${string}` | ''}` | `/Text/TextHome${`?${string}` | `#${string}` | ''}` | `/Text/TextMovilidad${`?${string}` | `#${string}` | ''}` | `/Text/TextReportProblem${`?${string}` | `#${string}` | ''}` | `/Text/TextRoomS${`?${string}` | `#${string}` | ''}` | `/Text/TextServices${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLHome`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLMovilidad`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLReportProblem`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLRoomS`; params?: Router.UnknownInputParams; } | { pathname: `/ASL/ASLServices`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextHome`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextMovilidad`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextReportProblem`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextRoomS`; params?: Router.UnknownInputParams; } | { pathname: `/Text/TextServices`; params?: Router.UnknownInputParams; };
    }
  }
}
